# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title                       : "At the Interface of Algebra and Neural Networks"
author                      : Clay Curry
copyright                   : "2023"
logo                        : assets/logo.png
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
execute:
  execute_notebooks: force

repository:
  url: https://github.com/claycurry34/Math
html:
  use_repository_button: true


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_togglebutton
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    