# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title                       : "Deep Learning: A Representation Theoreical Perspective"
author                      : Clay Curry
copyright                   : "2023"
logo                        : assets/logo.png
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js